### ISSUE TITLE
This feature now seems to be included in VSCode

### ISSUE THREAD

**Issue by ZakCodes** [siegebell/scope-info#10]
The feature is called [Scope inspector][inspector] and works without installing anything extra in VSCode. You can click on [this link][inspector] for more info about it.

[inspector]: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

**Comment by ghost** [comment]
Late but this is for extensions APIs, there is no way to access TM scopes in the backend..

**Comment by ZakCodes** [comment]
Alright, I didn't know that. I'll close this issue then.
