### ISSUE TITLE
cannot find module 'scope-info'

### ISSUE THREAD

**Issue by adepase** [siegebell/scope-info#8]
I installed version 0.2.0.
When trying the example code I get the error in the subject.
I tried to add 
"scope-info": "^0.2.0" 
(and also tried 
"siegebell.scope-info": "^0.2.0" 
)
in "devDependencies" and also
"scope-info"
(and "siegebell.scope-info")
in extensionDependencies.

Maybe it's just that I have not so clear what are the correct actions to include an extension in my extension, but I also got a 
command 'extension.enableScopeHover' not found 
(see other comment in other already opened issue) and I think something went wrong with the extension installation.
Please, help me, it seems very interesting to support my DSL language completion needs

**Comment by adepase** [comment]
No more interested, found other tools, thank you

**Comment by max-kalganov** [comment]
I didn't get it too. Any advice of how to import scope-info into plugin? Thanks.
